on: [push]

- name: PyCharm Python Security Scanner
  uses: tonybaloney/pycharm-security@1.20.1

jobs:
  security_checks:
    runs-on: ubuntu-latest
    name: Execute the pycharm-security action
    steps:
      - uses: actions/checkout@v1
      - name: Run PyCharm Security
        uses: tonybaloney/pycharm-security@master
