on: [push]

jobs:
  style_check:
    runs-on: ubuntu-latest
    name: Style check
    steps:
    - uses: actions/checkout@v2
    - name: wemake-python-styleguide
      uses: wemake-services/wemake-python-styleguide
      with:
        reporter: 'github-pr-review'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
